routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale){
    $locale = $locale == 'ne' ? 'ne' : 'en';
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('/albums', 'HomeController@albums');
Route::get('/albums/{slug}', 'HomeController@albumImages');

Route::get('/notices', 'HomeController@notices');

Route::get('/news','HomeController@news');
Route::get('/news/{slug}','HomeController@singleNews');


Route::get('/reports', 'HomeController@reports');
Route::get('/reports/filter', 'HomeController@filterReports');
Route::get('/report/print', 'HomeController@printReport');

Route::get('/projects','HomeController@projects');
Route::get('/projects/{slug}','HomeController@singleProject');

Route::get('contact-us','HomeController@contact_us')->name('contact');
Route::post('contact-us','HomeController@contactSend')->name('contactSend');

Route::get('/citizen-charter','HomeController@citizenCharter');

Route::get('/','HomeController@index')->name('home');

// Route::get('/about', function () {
//     return view('frontend.about');
// });

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('infos', 'Admin\InfoController',['except' => ['create']]);
    Route::resource('projects', 'Admin\ProjectController',['except' => ['create']]);
    Route::resource('notices', 'Admin\NoticeController',['except' => ['create']]);
    Route::resource('news', 'Admin\NewsController',['except' => ['create']]);
    Route::resource('reports', 'Admin\ReportController',['except' => ['create']]);
    Route::resource('personnels', 'Admin\PersonnelController',['except' => ['create']]);
    Route::resource('citizencharters', 'Admin\CitizenCharterController',['except' => ['create']]);

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::post('gallery/editcaption','Admin\AlbumController@editCaption');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    // Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('optimize');

Route::get('{alias}', 'HomeController@info');

app/CitizenCharter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CitizenCharter extends Model
{
    public function getServiceTitleAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_service_title'} ? : $this->en_service_title;
    }

    public function getServiceFeeAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_service_fee'} ? : $this->en_service_fee;
    }

    public function getServiceTimeAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_service_time'} ? : $this->en_service_time;
    }

    public function getResponsibleDeptAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_responsible_dept'} ? : $this->en_responsible_dept;
    }

    public function getRemarksAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_remarks'} ? : $this->en_remarks;
    }
}

app/Info.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Info extends Model
{
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'en_title'
            ]
        ];
    }

    public function getTitleAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_title'} ? : $this->en_title;
    }

    public function getDescriptionAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_description'} ? : $this->en_description;
    }
}

app/Personnel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personnel extends Model
{
    
    public function getNameAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_name'} ? : $this->en_name;
    }
    public function getDepartmentAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_department'} ? : $this->en_department;
    }
    public function getDesignationAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_designation'} ? : $this->en_designation;
    }

    public function getDescriptionAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_description'} ? : $this->en_description;
    }
}

resources/views/frontend/about.blade.php
@extends('layouts.app')
@section('title','About Us')

@section('body')
<section class="g-my-40">
    <div class="container">
        <div class="text-center">
            <h4 class="g-mb-20">Title 1</h4>
        </div>
        <div class="g-mb-60">
            <p> Hundreds of millions of online accounts were compromised in corporate data breaches, the US presidential
              election process was plagued by cyber-meddling, internet infrastructure companies faced massive digital attacks that disrupted web connectivity for millions of people, and Apple faced off with the FBI in an epic privacy battle. When reality
              is more terrifying than a movie could ever be, perhaps it's time to retreat into the fictional for awhile and enjoy the fascinating world of cybersecurity from the safety of your living room for a change. Here are some favorite movies and
              television shows from 2016 that will let you get a taste of the hacker underworld over the holidays—hopefully without consigning you to a permanent state of digital dread. We aim high at being focused on building relationships with our clients
              and community. Using our creative gifts drives this foundation.</p>
          </div>

    </div>
</section>
@endsection

resources/views/frontend/album_images.blade.php
@extends('layouts.app')

@section('title',$album->name)

@section('body')

        
        
</div>
<section class="g-my-40">
  <div class="container">
    <div class="text-center">
    <h4 class="g-mb-20"><a href="/albums">Albums </a>| {{$album->name}}</h4>
    </div>
    <div class="row">
        @foreach($images as $image)
            <div class="col-md-4 g-mb-30">
                <a class="js-fancybox d-block u-block-hover" href="javascript:;" data-fancybox="lightbox-gallery--03" data-src="/gallery/{{$image->image}}" data-speed="350" data-caption="{{ $image->caption }}">
                    <img class="img-fluid u-block-hover__main--mover-right" src="/gallery/{{$image->image}}" alt="Image Description">
                </a>
                <header class="u-bg-overlay__inner g-pos-abs g-bottom-30 g-right-30 g-left-30 g-color-white">
                    <h3 class="h4">{{ $image->caption }}</h3>
                </header>
            </div>
        @endforeach
       
    </div>
     <!-- Pagination -->
    <nav class="g-mt-50 text-center" aria-label="Page Navigation">
        {{ $images->appends(request()->except('page'))->links('frontend.partials.pagination') }}
    </nav>
    <!-- End Pagination -->

    </div>
</section>

@endsection

resources/views/frontend/albums.blade.php
@extends('layouts.app')

@section('title',trans('labels.nav.gallery'))

@section('body')
<section class="g-my-40">
  <div class="container">
   <div class="text-center">
        <h4 class="g-mb-20">Albums</h4>
    </div>
    <div class="row">
      @foreach($albums as $album)
      @if($album->album_images->count()>0)
      <div class="col-md-6 g-mb-30--md">
        <article class="u-block-hover g-rounded-6">
          <figure class="u-bg-overlay g-bg-black-opacity-0_4--after">
            <img class="img-fluid u-block-hover__main--zoom-v1" src="/gallery/{{$album->album_images->first()->image}}" alt="Image Description">
          </figure>
          <header class="u-bg-overlay__inner g-pos-abs g-top-30 g-right-30 g-left-30 g-color-white">
            <h3 class="h4 g-color-white">{{$album->name}}</h3>
            {{$album->year}}
          </header>
          
          <a class="u-link-v2" href="/albums/{{$album->slug}}" >Read More
          </a>
        </article>
      </div>
      @endif
      @endforeach
    </div>
    <nav class="g-mt-50 text-center" aria-label="Page Navigation">
        {{ $albums->appends(request()->except('page'))->links('frontend.partials.pagination') }}
    </nav>
  </div>
</section>

@endsection

@section('js')
{{-- <script  src="/frontend/main-assets/assets/js/components/hs.popup.js"></script> --}}

<!-- JS Plugins Init. -->
<script >
  $(document).on('ready', function () {
    // initialization of popups
    // $.HSCore.components.HSPopup.init('.js-fancybox');
  });
</script>
@endsection

resources/views/frontend/citizen_charter.blade.php
@extends('layouts.app')

@section('title',trans('labels.nav.citizenCharter'))

@section('body')
<section class="g-my-40">
    <div class="container">
        <div class="text-center">
            <h4 class="g-mb-20">@lang('labels.nav.citizenCharter')</h4>
        </div>
        <div class="g-mb-60">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Service Title</th>
                            <th>Service Fee</th>
                            <th>Service Time</th>
                            <th>Department</th>
                            <th>Remarks</th>

                        </tr>
                        </thead>
                    
                        <tbody>
                            @foreach($charters as $charter)
                        <tr>
                            <td>{{$charter->service_title}}</td>
                            <td>{{$charter->service_fee}}</td>
                            <td>{{$charter->service_time}}</td>
                            <td>{{$charter->responsible_dept}}</td>
                            <td>{{$charter->remarks}}</td>

                            
                        </tr>
                        @endforeach
                        
                        </tbody>
                    </table>
                    </div>
        </div>
    
    </div>
</section>

@endsection

resources/views/frontend/contact.blade.php
@extends('layouts.app')

@section('title',trans('labels.nav.contact'))

@section('body')
<div class="container">
    <br>

    <div class="g-my-60">
        <div class="u-heading-v3-1 g-mb-30">
            <h2 class="h5 u-heading-v3__title g-color-gray-dark-v1 text-uppercase g-brd-primary">@lang('labels.general.leave_a_message')</h2>
        </div>

        <form method="POST" action="{{ route('contactSend') }}">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-6 form-group g-mb-30">
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus rounded-3 g-pa-10" type="text" value="{{ old('name') }}" placeholder="Your Name" name="name" required>
                </div>

                <div class="col-md-6 form-group g-mb-30">
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus rounded-3 g-pa-10" type="email" value="{{ old('email') }}" placeholder="Email" name="email" required>
                </div>

                <div class="col-md-12 form-group g-mb-30">
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus rounded-3 g-pa-10" type="text" value="{{ old('subject') }}" placeholder="Subject" name="subject" required>
                </div>
            </div>

            <div class="g-mb-30">
                <textarea class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--focus g-resize-none rounded-3 g-pa-15" rows="12" placeholder="Your Message" name="message" required>{{ old('message') }}</textarea>
            </div>

            <button class="btn u-btn-primary g-font-size-12 text-uppercase g-px-25 g-py-13" type="submit">
                <i class="icon-finance-206 u-line-icon-pro align-middle g-pos-rel g-top-1 mr-2"></i> @lang('labels.general.send')
            </button>
        </form>
    </div>
</div>

@if(Session::has('contact_success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert" style="position: fixed;right: 2rem; bottom: 2px;z-index: 2;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="h5">
            <i class="fa fa-check-circle-o"></i>
            Success!
        </h4>
        @lang('labels.general.contact_success')
    </div>
@endif

@if(Session::has('contact_error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="position: fixed;right: 2rem; bottom: 2px;    z-index: 2;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="h5">
            <i class="fa fa-check-circle-o"></i>
            Error!
        </h4>
        @lang('labels.general.contact_error')        
    </div>
@endif

@stop

resources/views/frontend/info.blade.php
@extends('layouts.app')

@section('title',$info->title)

@section('body')
<section class="g-my-40">
    <div class="container">
        <div class="text-center">
            <h4 class="g-mb-20">{{ $info->title }}</h4>
        </div>
        <div class="g-mb-60">
            {!! $info->description !!}
        </div>
    
    </div>
</section>

@endsection

resources/views/frontend/news.blade.php
@extends('layouts.app')

@section('title',trans('labels.nav.news'))

@section('body')

    <section class="g-my-40">
        <div class="container">
            <div class="text-center">
                <h4 class="g-mb-20">Latest Updates</h4>
            </div>
            <div class="row">
                @foreach ($newsList as $news)
                    <div class="col-lg-4 g-mb-30">
                        <!-- Article -->
                        <article class="g-bg-white">
                            <figure class="g-pos-rel">
                                <img class="img-fluid w-100" src="{{ route('optimize', ['news_images',$news->image,350,300]) }}" alt="{{ $news->title }}">
                                <figcaption class="text-uppercase text-center g-line-height-1_2 g-bg-primary-opacity-0_8 g-color-white g-pos-abs g-top-20 g-px-15 g-py-10">
                                    <strong class="d-block">{{ date('j M',strtotime($news->published_date)) }}</strong>
                                    <hr class="g-brd-white my-1">
                                    <small class="d-block">{{ date('Y',strtotime($news->published_date)) }}</small>
                                </figcaption>
                            </figure>
        
                            <div class="g-pa-30">
                                <h3 class="h5 g-mb-15">
                                    <a class="u-link-v5 g-color-gray-dark-v2 g-color-primary--hover" href="/news/{{ $news->slug }}">{{ $news->title }}</a>
                                </h3>
        
                                <p>
                                    {{ (str_limit(strip_tags($news->description), $limit = 170, $end = '...')) }}
                                </p>
        
                                {{-- <hr class="g-brd-gray-light-v4 g-my-20">
        
                                <ul class="list-inline small text-uppercase mb-0">
                                    <li class="list-inline-item">
                                        <span class="g-color-gray-dark-v4">By</span>
                                        <a class="u-link-v5 g-color-main g-color-primary--hover" href="#">Kathy Reyes</a>
                                    </li>
                                    <li class="list-inline-item">-</li>
                                    <li class="list-inline-item">
                                        <i class="icon-bubbles align-middle g-color-gray-dark-v4 g-mr-2"></i>
                                        32 commetns
                                    </li>
                                </ul> --}}
                            </div>
                        </article>
                        <!-- End Article -->
                    </div>
                @endforeach
                
            </div>
            <nav class="text-center" aria-label="Page Navigation">
                {!! $newsList->links('frontend.partials.paginate') !!}  
            </nav>

        </div>
    </section>
@endsection

resources/views/frontend/personnels.blade.php
@extends('layouts.app')

@section('title',trans('labels.nav.personnels'))

@section('body')

<section class="g-my-40 g-mx-20">
        <div class="row">

            <div class="col-sm-12 col-lg-8 col-md-8">
                  <div class="text-center">
                      <h4 class="g-mb-40">Personnels</h4>
                  </div>
                  <div id="carouselCus3" class="js-carousel g-mb-50--lg" data-infinite="true" data-fade="true" data-lazy-load="ondemand" data-arrows-classes="u-arrow-v1 g-absolute-centered--y g-width-45 g-height-45 g-font-size-30 g-color-gray-dark-v4 g-color-primary--hover" data-arrow-left-classes="fa fa-angle-left g-left-0 g-left-40--lg" data-arrow-right-classes="fa fa-angle-right g-right-0 g-right-40--lg" data-nav-for="#carouselCus4">
                    @foreach($personnels as $person)  
                    <div class="js-slide">
                        <!-- Team -->
                        <div class="row justify-content-center align-items-center no-gutters">
                        <div class="col-sm-6 col-lg-4 g-bg-size-cover g-bg-pos-top-center g-min-height-400" data-bg-img-src="/personnel_images/{{$person->image}}"></div>
                          <div class="col-sm-6 col-lg-4">
                            <div class="g-px-3 g-px-30--lg g-py-60">
                              <h3 class="h4 mb-1">{{$person->name}}</h3>
                              <span class="d-block">{{$person->designation}}</span>
                              <span class="d-block mb-4">{{$person->department}}</span>

                            <p class="mb-4">{{$person->description}}</p>
                    
                            </div>
                          </div>
                        </div>
                        <!-- End Team -->
                      </div>
                      @endforeach
                    
                  </div>
                    
                  <div id="carouselCus4" class="js-carousel text-center u-carousel-v3 g-mx-minus-15" data-infinite="true" data-center-mode="true" data-slides-show="5" data-is-thumbs="true" data-lazy-load="ondemand" data-nav-for="#carouselCus3">
                   @foreach($personnels as $person)
                    <div class="js-slide g-opacity-1 g-cursor-pointer g-px-15">
                    <img class="img-fluid mb-3" src="/personnel_images/{{$person->image}}" alt="{{$person->name}}">
                      <h3 class="h6 g-color-gray-dark-v4">{{$person->name}}</h3>
                    </div>
                    @endforeach
                  
                  
                  </div>
              </div>

              <div class="col-md-3 g-ml-30 g-mt-10" >
                  <div class="text-center g-brd-primary" style="border:1px solid; padding:1rem; border-radius:10px">
                      <h4 class="g-mb-20">Project Report</h4>

                      <a href="/reports" class="btn btn-primary">View Report.</a>
                  </div>
                  <hr>

                  <div class="text-center">
                      <h4 class="g-mb-20">Notices</h4>
                  </div>
                  <ul class="list-unstyled">
                    @foreach($notices as $notice)
                      <li class="g-brd-around g-brd-gray-light-v4 g-pa-20 g-mb-minus-1">
                        <div class="media">
                          <div class="media-body">
                          <p class="m-0">{{$notice->title}}</p>
                            <span class="g-font-size-12 g-color-gray">{{$notice->published_date}}</span>
                          </div>
                        </div>
                      </li>
                      @endforeach
                    </ul>
                    <div class="text-center">
                        <a href="/notices" class="btn btn-primary">View All.</a>

                    </div>
                    

              </div>
        

        </div>
      </section>
@endsection

resources/views/frontend/singlenews.blade.php
@extends('layouts.app')

@section('title',$news->title)

@section('body')

    <section class="g-my-40">
        <div class="container">
            <div class="row">
                <article class="g-mb-60">
                    <header class="g-mb-30">
                        <h2 class="h1 g-mb-15">{{ $news->title }}</h2>
            
                        <ul class="list-inline d-sm-flex g-color-gray-dark-v4 mb-0">
                            {{-- <li class="list-inline-item">
                                <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">Mike Coolman</a>
                            </li>
                            <li class="list-inline-item g-mx-10">/</li> --}}
                            <li class="list-inline-item">
                                {{ date('M j, Y',strtotime($news->published_date)) }}
                            </li>
                        </ul>
        
                        {{-- <hr class="g-brd-gray-light-v4 g-my-15">
        
                        <ul class="list-inline text-uppercase mb-0">
                            <li class="list-inline-item g-mr-10">
                                <a class="btn u-btn-facebook g-font-size-12 rounded g-px-20--sm g-py-10" href="#!">
                                    <i class="fa fa-facebook g-mr-5--sm"></i> <span class="g-hidden-xs-down">Share on Facebook</span>
                                </a>
                            </li>
                            <li class="list-inline-item g-mr-10">
                                <a class="btn u-btn-twitter g-font-size-12 rounded g-px-20--sm g-py-10" href="#!">
                                    <i class="fa fa-twitter g-mr-5--sm"></i> <span class="g-hidden-xs-down">Tweet on Twitter</span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="btn u-btn-lightred g-font-size-12 rounded g-py-10" href="#!">
                                    <i class="fa fa-pinterest"></i>
                                </a>
                            </li>
                        </ul> --}}
                    </header>
            
                    <div class="g-font-size-16 g-line-height-1_8 g-mb-30">
                        <figure class=" g-mb-30">
                            <img class="img-fluid" src="{{ asset('news_images/'.$news->image) }}" alt="{{ $news->title }}">
                        </figure>  
                    </div>
            
                    {!! $news->description !!}
                </article>
            </div>

        </div>
    </section>
@endsection

resources/views/frontend/singleproject.blade.php
@extends('layouts.app')

@section('title',$project->title)

@section('body')

    <section class="g-my-40">
        <div class="container">
            <div class="row">
                <article class="g-mb-60">
                    <header class="g-mb-30">
                        <h2 class="h1 g-mb-15">{{ $project->title }}</h2>
            
                        <ul class="list-inline d-sm-flex g-color-gray-dark-v4 mb-0">
                            {{-- <li class="list-inline-item">
                                <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">Mike Coolman</a>
                            </li>
                            <li class="list-inline-item g-mx-10">/</li> --}}
                        
                        </ul>
        
                        {{-- <hr class="g-brd-gray-light-v4 g-my-15">
        
                        <ul class="list-inline text-uppercase mb-0">
                            <li class="list-inline-item g-mr-10">
                                <a class="btn u-btn-facebook g-font-size-12 rounded g-px-20--sm g-py-10" href="#!">
                                    <i class="fa fa-facebook g-mr-5--sm"></i> <span class="g-hidden-xs-down">Share on Facebook</span>
                                </a>
                            </li>
                            <li class="list-inline-item g-mr-10">
                                <a class="btn u-btn-twitter g-font-size-12 rounded g-px-20--sm g-py-10" href="#!">
                                    <i class="fa fa-twitter g-mr-5--sm"></i> <span class="g-hidden-xs-down">Tweet on Twitter</span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="btn u-btn-lightred g-font-size-12 rounded g-py-10" href="#!">
                                    <i class="fa fa-pinterest"></i>
                                </a>
                            </li>
                        </ul> --}}
                    </header>
            
                    <div class="g-font-size-16 g-line-height-1_8 g-mb-30">
                        <figure class=" g-mb-30">
                            <img class="img-fluid" src="{{ asset('project_images/'.$project->image) }}" alt="{{ $project->title }}">
                        </figure>  
                    </div>
            
                    {!! $project->description !!}
                </article>
            </div>

        </div>
    </section>
@endsection