routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale){
    $locale = $locale == 'ne' ? 'ne' : 'en';
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('/albums', 'HomeController@albums');
Route::get('/albums/{slug}', 'HomeController@albumImages');

Route::get('/notices', 'HomeController@notices');

Route::get('/news','HomeController@news');
Route::get('/news/{slug}','HomeController@singleNews');


Route::get('/reports', 'HomeController@reports');
Route::get('/reports/filter', 'HomeController@filterReports');
Route::get('/report/print', 'HomeController@printReport');

Route::get('/projects','HomeController@projects');
Route::get('/projects/{slug}','HomeController@singleProject');

Route::get('contact-us','HomeController@contact_us')->name('contact');
Route::post('contact-us','HomeController@contactSend')->name('contactSend');

Route::get('/citizen-charter','HomeController@citizenCharter');

Route::get('/','HomeController@index')->name('home');

// Route::get('/about', function () {
//     return view('frontend.about');
// });

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('infos', 'Admin\InfoController',['except' => ['create']]);
    Route::resource('projects', 'Admin\ProjectController',['except' => ['create']]);
    Route::resource('notices', 'Admin\NoticeController',['except' => ['create']]);
    Route::resource('news', 'Admin\NewsController',['except' => ['create']]);
    Route::resource('reports', 'Admin\ReportController',['except' => ['create']]);
    Route::resource('personnels', 'Admin\PersonnelController',['except' => ['create']]);
    Route::resource('citizencharters', 'Admin\CitizenCharterController',['except' => ['create']]);

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::post('gallery/editcaption','Admin\AlbumController@editCaption');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    // Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('optimize');

Route::get('{alias}', 'HomeController@info');

app/Info.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Info extends Model
{
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'en_title'
            ]
        ];
    }

    public function getTitleAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_title'} ? : $this->en_title;
    }

    public function getDescriptionAttribute(){
        $locale = app()->getLocale();

        return $this->{$locale.'_description'} ? : $this->en_description;
    }
}

app/Http/Controllers/Admin/InfoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Info;

class InfoController extends Controller
{
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index()
    {
        $infos = Info::orderBy('updated_at','desc')->paginate(10);
        
        return view('admin.infos.index')->with('infos',$infos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([         
            'en_title' => 'required|max:191',
            'en_description' => 'required',
        ]);

        $info = new Info;
        $info->en_title = $request->en_title;
        $info->ne_title = $request->ne_title;
        $info->en_description = $request->en_description;
        $info->ne_description = $request->ne_description;

        $info->save();

        $request->session()->flash('success', 'Info added.');        
        
        return redirect()->route('infos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $info = Info::findOrFail($id);

        return view('admin.infos.show',compact('info'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $info = Info::findOrFail($id);

        return view('admin.infos.edit',compact('info'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([          
            'en_title' => 'required|max:191',
            'en_description' => 'required',
        ]);

        $info = Info::findOrFail($id);
        $info->en_title = $request->en_title;
        $info->ne_title = $request->ne_title;
        $info->en_description = $request->en_description;
        $info->ne_description = $request->ne_description;

        $info->save();

        $request->session()->flash('success', 'Info updated.');        
        
        return redirect()->route('infos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $info = Info::findOrFail($id);
        $info->delete();

        $request->session()->flash('success', 'Info deleted.');        
        
       return redirect()->back();
    }
 
}

resources/views/admin/infos/edit.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Edit Info</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('infos.update',$info->id) }}"  enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PATCH" >

                        <h4 class="form-section"><i class="icon-eye6"></i> Info Post</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="title">Title</label>
                                    <input class="form-control{{ $errors->has('en_title') ? ' border-danger' : '' }}" id="en_title" type="text" class="form-control" name="en_title" value="{{ $info->en_title }}" required autofocus>

                                    @if ($errors->has('en_title'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('en_title') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="title">टाइटल
                                    </label>
                                    <input class="form-control{{ $errors->has('ne_title') ? ' border-danger' : '' }}" id="ne_title" type="text" class="form-control" name="ne_title" value="{{ $info->ne_title }}">

                                    @if ($errors->has('ne_title'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('ne_title') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Details</label>
                                    @if ($errors->has('en_description'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('en_description') }}</strong>
                                        </div>
                                    @endif
                                    <textarea cols="50" rows="20" class="content form-control{{ $errors->has('en_description') ? ' border-danger' : '' }}" id="en_content" name="en_description">{{ $info->en_description }}</textarea>
                            
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>डिटेल</label>
                                    @if ($errors->has('ne_description'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('ne_description') }}</strong>
                                        </div>
                                    @endif
                                    <textarea cols="50" rows="20" class="content form-control{{ $errors->has('ne_description') ? ' border-danger' : '' }}" id="ne_content" name="ne_description">{{ $info->ne_description }}</textarea>
                            
                                </div>
                            </div>
                        </div>
                           
                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea.content",
           
           plugins: [
               "advlist autolink lists link charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link",
           toolbar2: "print preview | forecolor backcolor emoticons"
       });
   </script>
  
@endsection

resources/views/admin/infos/index.blade.php
@extends('layouts.admin')

@section('body')
   
   <div class="content-header row">
   </div>
   <input name="image" type="file" id="upload" class="hidden" onchange="">

   <div class="content-body">
       <div class="card">
           <div class="card-header">
               <h4 class="card-title"><a data-action="collapse">Add New Info</a></h4>
               <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
               <div class="heading-elements">
                   <ul class="list-inline mb-0">
                       <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                       <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                   </ul>
               </div>
           </div>
           <div class="card-body collapse {{ count($errors)>0 ? 'in':'out' }}">
               <div class="card-block card-dashboard">
                   <form class="form" method="POST" id="AddInfoForm" action="{{ route('infos.store') }}" enctype="multipart/form-data">
                       {{ csrf_field() }}
                       <div class="form-body">
                            <h4 class="form-section"><i class="icon-eye6"></i> Info</h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input class="form-control{{ $errors->has('en_title') ? ' border-danger' : '' }}" id="en_title" type="text" class="form-control" name="en_title" value="{{ old('en_title') }}" required>

                                        @if ($errors->has('en_title'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('en_title') }}</strong>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">टाइटल
                                        </label>
                                        <input class="form-control{{ $errors->has('ne_title') ? ' border-danger' : '' }}" id="ne_title" type="text" class="form-control" name="ne_title" value="{{ old('ne_title') }}">

                                        @if ($errors->has('ne_title'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('ne_title') }}</strong>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                          
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Details</label>
                                        @if ($errors->has('en_description'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('en_description') }}</strong>
                                            </div>
                                        @endif
                                        <textarea cols="50" rows="20" class="content form-control{{ $errors->has('en_description') ? ' border-danger' : '' }}" id="en_content" name="en_description">{{ old('en_description') }}</textarea>
                                
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>डिटेल</label>
                                        @if ($errors->has('ne_description'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('ne_description') }}</strong>
                                            </div>
                                        @endif
                                        <textarea cols="50" rows="20" class="content form-control{{ $errors->has('ne_description') ? ' border-danger' : '' }}" id="ne_content" name="ne_description">{{ old('ne_description') }}</textarea>
                                
                                    </div>
                                </div>
                            </div>
                       </div>

                       <div class="form-actions right">
                           <button type="submit" class="btn btn-primary">
                               <i class="icon-check2"></i> Save
                           </button>
                       </div>
                   </form>
               </div>
           </div>
       </div>

       <div class="card">
           <div class="card-header">
               <h4 class="card-title">Info Posts</h4>
               <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
               <div class="heading-elements">
                   <ul class="list-inline mb-0">
                       <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                       <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                   </ul>
               </div>
           </div>
           <div class="card-body collapse in">
               <div class="card-block card-dashboard">
                   <div class="table-responsive">
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>#</th>
                                   <th>Title</th>
                                   <th width="20%">Actions</th>
                               </tr>
                           </thead>
                           <tbody>
                               @foreach($infos as $info)
                               <tr>
                                   <td>{{ $loop->iteration + (($infos->currentPage()-1) * $infos->perPage()) }}</td>
                                   <td>{{ $info->en_title }}</td>
                                    <td>
                                        <a class="btn btn-outline-primary" title="View Details" href="{{ route('infos.show',$info->id) }}"><i class="icon-eye"></i></a>

                                       <a class="btn btn-outline-warning" title="Update Details" href="{{ route('infos.edit',$info->id) }}"><i class="icon-edit"></i></a>
                                       
                                       <form action="{{ route('infos.destroy',$info->id) }}" method="POST" style="display:inline">
                                           {{ csrf_field() }}
                                           <input type="hidden" name="_method" value="DELETE" >
                                           <button id='deleteInfo{{ $info->id }}' type="button" class="btn btn-outline-danger"><i class="icon-trash-o"></i></button>
                                       </form>
                                   </td>
                               </tr>
                               @endforeach
                           </tbody>
                       </table>


                       <div class="text-xs-center mb-3">
                           <nav aria-label="Page navigation">
                               {{ $infos->links() }}
                           </nav>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>

   
@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea.content",
           
           plugins: [
               "advlist autolink lists link charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link",
           toolbar2: "print preview | forecolor backcolor emoticons"
       });

   </script>
  
@endsection

resources/views/admin/infos/show.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Info #{{ $info->id }}</h2>
        </div>
        <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
            <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                    <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ route('infos.index') }}">Back</a>
                    <a class="btn btn-warning btn-min-width mr-1 mb-1 " href="{{ route('infos.edit',$info->id) }}">Edit</a>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section class="card">
            <div class="card-body collapse in">
                <div class="card-block">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" id="english-tab" data-toggle="tab" href="#english" aria-controls="english" aria-expanded="true">English</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="nepali-tab" data-toggle="tab" href="#nepali" aria-controls="nepali" aria-expanded="false">Nepali</a>
                        </li>
                    </ul>
                    <div class="tab-content px-1 pt-1">
                        <div role="tabpanel" class="tab-pane fade active in" id="english" aria-labelledby="english-tab" aria-expanded="true">
                                
                            <div id="invoice-template" class="card-block">
                                
                                <div id="invoice-items-details" class="pt-2">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="text-xs-center">
                                                <h2>{{ $info->en_title }} </h2>
                                            </div><br>
                                            <p>{!! $info->en_description !!}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade in" id="nepali" aria-labelledby="nepali-tab" aria-expanded="true">
                                
                            <div id="invoice-template" class="card-block">
                                
                                <div id="invoice-items-details" class="pt-2">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="text-xs-center">
                                                <h2>{{ $info->ne_title }} </h2>
                                            </div><br>
                                            <p>{!! $info->ne_description !!}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection